{{- if or .Values.ap.transportConfig .Values.ap.workerPools .Values.ap.transformConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "async-processor.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "async-processor.labels" . | nindent 4 }}
data:
  {{- if .Values.ap.transportConfig }}
  transport.json: {{ .Values.ap.transportConfig | toJson | quote }}
  {{- end }}
  {{- if .Values.ap.workerPools }}
  worker-pools.json: {{ .Values.ap.workerPools | toJson | quote }}
  {{- end }}
  {{- if .Values.ap.transformConfig }}
  transform-config.json: {{ .Values.ap.transformConfig | toJson | quote }}
  {{- end }}
{{- end }}
